config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :ratings, only: [:new, :create]
  resources :friendships, only: [:new]
  resources :users, only: [:show, :edit] do
    resources :friendships, only: [:create, :show, :edit, :update]

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ratings
  has_many :restaurants, through: :ratings
  has_many :friendships
  has_many :favorites
  has_many :favorite_restaurants, through: :favorites, source: :restaurant

  validates :first_name, presence:true
  validates :last_name, presence:true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_show = User.find(params[:id])

    @friendships = current_user.friendships.select do |friendship|
      friendship.status == "pending"
    end
    @friendships_two = @friendships.select do |friendship|
      friendship.action != 'yes'
    end
    @friends = []
    @friendships_two.each do |friendship|
      @friends << friendship.friend
    end

    @friendships_bestätigt = @user_show.friendships.select do |friendship|
      friendship.status = 'accepted'
    end

    @friends_bestätigt = @friendships_bestätigt.each do |friendship|
      friendship.friend
    end
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<div class="wrapper">
  <div class="user-details">
    <div class="user-photo-edit">
      <%= cl_image_tag current_user.photo, width: 200, height: 200, crop: :thumb, gravity: :face%>
    </div>
  </div>
  <div class="line-show"></div>
<!--   <div class="menu-edit-profile">
    <div class="menu-edit-profile-1">
      <i class="fas fa-user-edit"></i>
    </div>
    <div class="menu-edit-profile-2">
      <i class="fas fa-paperclip"></i>
    </div>
  </div>
  <div class="line-show"></div> -->
  <div class="edit-profile-page">
    <h4>Private information</h4>
    <div class="private-information">
      <div class="private-information-name">
        <p>Name</p> <p>Email</p><p>Change password</p>
      </div>
      <div class="private-information-email">
         <p><%= current_user.first_name %> <%= current_user.last_name %></p><p><%= current_user.email %></p><p><%= link_to "Click here", edit_user_registration_path %></p>
      </div>
    </div>
  </div>
  <div class="imprint">
    <h4>Impressum</h4>
    <p>Informationspflicht laut §5 E-Commerce Gesetz, §14 Unternehmensgesetzbuch, §63 Gewerbeordnung und Offenlegungspflicht laut §25 Mediengesetz.</p>

    <h5>MusterFirma GmbH
    Musterstrasse 1, Stiege 1 Tür 1,
    1234 Musterhausen,
    Österreich/Deutschland</h5>

    <p>Unternehmensgegenstand: IT Dienstleistungen
    UID-Nummer: ATU12345678
    Firmenbuchnummer: 123456a
    Firmenbuchgericht: Musterhausen
    Firmensitz: 1234 Musterhausen</p>

    <p>Tel.: 01234/56789
    Fax: 01234/56789-0
    E-Mail: office@musterfirma.com</p>

    <p>Mitglied bei: WKO, Landesinnung, etc.
    Berufsrecht: Gewerbeordnung: www.ris.bka.gv.at</p>

    <p><strong>Aufsichtsbehörde/Gewerbebehörde:</strong> Bezirkshauptmannschaft Musterhausen</p>

    <p><strong>Geschäftsführer:</strong>
    Markus Muster, Thomas Muster<p>

    <h4>EU-Streitschlichtung</h4>
    <p>Gemäß Verordnung über Online-Streitbeilegung in Verbraucherangelegenheiten (ODR-Verordnung) möchten wir Sie über die Online-Streitbeilegungsplattform (OS-Plattform) informieren.
    Verbraucher haben die Möglichkeit, Beschwerden an die Online Streitbeilegungsplattform der Europäischen Kommission unter http://ec.europa.eu/odr zu richten. Die dafür notwendigen Kontaktdaten finden Sie oberhalb in unserem Impressum.

    Wir möchten Sie jedoch darauf hinweisen, dass wir nicht bereit oder verpflichtet sind, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>

    <h4>Haftung für Inhalte dieser Webseite</h4>
    <p>Wir entwickeln die Inhalte dieser Webseite ständig weiter und bemühen uns korrekte und aktuelle Informationen bereitzustellen. Leider können wir keine Haftung für die Korrektheit aller Inhalte auf dieser Webseite übernehmen, speziell für jene die seitens Dritter bereitgestellt wurden.</p>

    <p>Sollten Ihnen problematische oder rechtswidrige Inhalte auffallen, bitte wir Sie uns umgehend zu kontaktieren, Sie finden die Kontaktdaten im Impressum.<p>

    <h4>Haftung für Links auf dieser Webseite</h4>
    <p>Unsere Webseite enthält Links zu anderen Webseiten für deren Inhalt wir nicht verantwortlich sind. Haftung für verlinkte Websites besteht laut § 17 ECG für uns nicht, da wir keine Kenntnis rechtswidriger Tätigkeiten hatten und haben, uns solche Rechtswidrigkeiten auch bisher nicht aufgefallen sind und wir Links sofort entfernen würden, wenn uns Rechtswidrigkeiten bekannt werden.</p>

    <p>Wenn Ihnen rechtswidrige Links auf unserer Website auffallen, bitte wir Sie uns zu kontaktieren, Sie finden die Kontaktdaten im Impressum.</p>

    <h4>Urheberrechtshinweis</h4>
    <p>Alle Inhalte dieser Webseite (Bilder, Fotos, Texte, Videos) unterliegen dem Urheberrecht. Falls notwendig, werden wir die unerlaubte Nutzung von Teilen der Inhalte unserer Seite rechtlich verfolgen.</p>

    <h4>Bildernachweis</h4>
    <p>Die Bilder, Fotos und Grafiken auf dieser Webseite sind urheberrechtlich geschützt.

    Die Bilderrechte liegen bei den folgenden Fotografen und Unternehmen:</p>

    <h4>Fotograf Mustermann</h4>

    <h4>Datenschutzerklärung</h4>
    <h4>Datenschutz</h4>
    <p>Wir haben diese Datenschutzerklärung (Fassung 12.07.2018-221067512) verfasst, um Ihnen gemäß der Vorgaben der Datenschutz-Grundverordnung (EU) 2016/679 und dem Datenschutzgesetz (DSG) zu erklären, welche Informationen wir sammeln, wie wir Daten verwenden und welche Entscheidungsmöglichkeiten Sie als Besucher dieser Webseite haben.

    Leider liegt es in der Natur der Sache, dass diese Erklärungen sehr technisch klingen, wir haben uns bei der Erstellung jedoch bemüht die wichtigsten Dinge so einfach und klar wie möglich zu beschreiben.</p>

    <h4>Speicherung persönlicher Daten</h4>
    <p>Persönliche Daten, die Sie uns auf dieser Website elektronisch übermitteln, wie zum Beispiel Name, E-Mail-Adresse, Adresse oder andere persönlichen Angaben im Rahmen der Übermittlung eines Formulars oder Kommentaren im Blog, werden von uns gemeinsam mit dem Zeitpunkt und der IP-Adresse nur zum jeweils angegebenen Zweck verwendet, sicher verwahrt und nicht an Dritte weitergegeben.

    Wir nutzen Ihre persönlichen Daten somit nur für die Kommunikation mit jenen Besuchern, die Kontakt ausdrücklich wünschen und für die Abwicklung der auf dieser Webseite angebotenen Dienstleistungen und Produkte. Wir geben Ihre persönlichen Daten ohne Zustimmung nicht weiter, können jedoch nicht ausschließen, dass diese Daten beim Vorliegen von rechtswidrigem Verhalten eingesehen werden.

    Wenn Sie uns persönliche Daten per E-Mail schicken – somit abseits dieser Webseite – können wir keine sichere Übertragung und den Schutz Ihrer Daten garantieren. Wir empfehlen Ihnen, vertrauliche Daten niemals unverschlüsselt per E-Mail zu übermitteln.

    Die Rechtsgrundlage besteht nach Artikel 6  Absatz 1 a DSGVO (Rechtmäßigkeit der Verarbeitung) darin, dass Sie uns die Einwilligung zur Verarbeitung der von Ihnen eingegebenen Daten geben. Sie können diesen Einwilligung jederzeit widerrufen – eine formlose E-Mail reicht aus, Sie finden unsere Kontaktdaten im Impressum.</p>

    <h4>Google Fonts Datenschutzerklärung</h4>
    <p>Wir verwenden Google Fonts der Firma Google Inc. (1600 Amphitheatre Parkway Mountain View, CA 94043, USA) auf unserer Webseite. Die Verwendung von Google Fonts erfolgt ohne Authentisierung und es werden keine Cookies and die Google Fonts API gesendet. Sollten Sie ein Konto bei Google haben, werden keine Ihrer Google-Kontodaten an Google während der Nutzung von Google Fonts übermittelt. Google erfasst lediglich die Nutzung von CSS und der verwendeten Fonts und speichert diese Daten sicher. Mehr zu diesen und weiteren Fragen finden Sie auf https://developers.google.com/fonts/faq.

    Welche Daten von Google erfasst werden und wofür diese Daten verwendet werden, können Sie auf https://www.google.com/intl/de/policies/privacy/ nachlesen.</p>

    Facebook Datenschutzerklärung
    <p>Wir verwenden auf dieser Webseite Funktionen von Facebook, einem Social Media Network der FIrma Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2 Ireland.
    Welche Funktionen (Soziale Plug-ins) Facebook bereitstellt, können Sie auf https://developers.facebook.com/docs/plugins/ nachlesen.
    Durch den Besuch unserer Webseite können Informationen an Facebook übermittelt werden. Wenn Sie über ein Facebook-Konto verfügen, kann Facebook diese Daten Ihrem persönlichen Konto zuordnen. Sollten Sie das nicht wünschen, melden Sie sich bitte von Facebook ab.
    Die Datenschutzrichtlinien, welche Informationen Facebook sammelt und wie sie diese verwenden finden Sie auf https://www.facebook.com/policy.php.</p>

    <h4>Instagram Datenschutzerklärung</h4>
    <p>Wir verwenden auf unserer Webseite Funktionen des Social Media Netzwerks Instagram der Firma Instagram LLC, 1601 Willow Rd, Menlo Park CA 94025, USA.

    Mit den Funktionen zum Einbetten von Instagram-Inhalten (Embed-Funktion) können wir Bilder und Videos anzeigen.

    Durch den Aufruf von Seiten die solche Funktionen nutzen werden Daten (IP-Adresse, Browserdaten, Datum, Uhrzeit, Cookies) an Instagram übermittelt, gespeichert und ausgewertet.

    Sollten Sie ein Instagram-Konto haben und angemeldet sein, werden diese Daten Ihrem persönlichen Konto und den darin gespeicherten Daten zugeordnet.

    Die Datenschutzrichtlinien, welche Informationen Instagram sammelt und wie sie diese verwenden finden Sie auf https://help.instagram.com/519522125107875.</p>
  </div>
</div>

<%= javascript_pack_tag 'edit-profile' %>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="user-details">
    <div class="user-photo-show">
      <%= cl_image_tag @user_show.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar"%>
    </div>
    <div class="number-friendships-reviews">
      <div class="number-reviews">
        <h4><%= @user_show.ratings.count %></h4>
        <p>reviews</p>
      </div>
      <div class="number-friendships">
        <%= link_to user_friendship_path(current_user) do %>
          <h4><%= @friends_bestätigt.count %></h4>
        <%end %>
        <p>friends</p>
      </div>
    </div>
    <%= link_to edit_user_path(current_user) do %>
      <div class="edit-profile-show">
        <h4>Edit profile</h4>
      </div>
    <%end %>
  </div>

  <div class="user-show-icons">
    <div class="line-show"></div>
    <div class="quick-facts">
      <div class="reviews-all-user">
        <i class="fas fa-list-ol"></i>
      </div>
      <div class="wishlist">
        <i class="fas fa-heart"></i>
      </div>
      <div class="Freundschaftsanfragen">
        <i class="fas fa-users"></i>
        <div class="Zahl">
          <% if @friends == [] %>
          <% else %>
            <div class="counter2">
              <%= @friends.count %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="line-show"></div>
  </div>
  <div class="user-reviews">
    <% if @user_show.ratings.count > 0 %>
      <% @user_show.ratings.each do |rating| %>
        <%= link_to restaurant_path(rating.restaurant) do %>
          <div class="user-review-show">
            <div class="image-user-show">
              <% unless rating.photo.blank? %>
                <%= cl_image_tag rating.photo %>
              <% else %>
                <%= image_tag("munich.jpg")%>
              <% end %>
            </div>
            <div class="image-user-show-facts">
              <div class="name-city-user">
                <h4><%= rating.restaurant.name %></h4>
                <p><%= rating.restaurant.city %></p>
              </div>
              <div class="stars-user">
                <span><%= rating.stars.to_f %></span> <i class="fas fa-star"></i>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="no-reviews-yet">
        <p> Add your first review of your favourite restaurant or bar
          <%= link_to new_rating_path do %>
            <span>here</span>.
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
  <div class="wishlist-user">
    <% if @user_show.ratings.count > 0 %>
      <% current_user.favorites.each do |f| %>
        <%= link_to restaurant_path(f.restaurant) do %>
          <div class="user-review-show">
            <div class="image-user-show">

              <% unless f.restaurant.ratings.first.photo.blank? %>
                <%= cl_image_tag f.restaurant.ratings.first.photo %>
              <% else %>
                <%= image_tag("munich.jpg")%>
              <% end %>
            </div>
            <div class="image-user-show-facts">
              <div class="name-city-user">
                <h4><%= f.restaurant.name %></h4>
                <p><%= f.restaurant.city %> <%= f.restaurant.country %></p>
              </div>
              <div class="stars-user">
                <span><%= @average.to_f %></span> <i class="fas fa-star"></i>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p> Have your friends already reviewed an amazing restaurant or bar you want to visit as well? Add it to your wishlist by clicking on the <i class="fas fa-heart"></i> of the specific restaurant or bar and start planning your visit.</p>
    <% end  %>
  </div>
  <div class="freundschaftsanfragen-list">
    <div class="display-friends">
      <% if @friends.empty? %>
        <div style="margin-top:15px;margin-bottom:15px">
          <div class="line"></div>
          <p> You don't have any friendship requests at the moment!</p>
        </div>
      <% else %>
        <p>Your friendship requests</p>
        <% @friends.each do |friend| %>
          <div style="margin-top:15px;margin-bottom:15px">
            <div class="line"></div>
          </div>
          <div class="users-info">
            <div class="profile-photo">
              <%= cl_image_tag friend.photo, width: 140, height: 140, crop: :thumb, gravity: :face, class:"avatar" %>
            </div>
            <div class="name">
              <%= friend.first_name %>
              <%= friend.last_name %>
            </div>
            <%@friendship_this = friend.friendships.where(friend_id: current_user) %>
            <div class="follow-button1" >
              <%= link_to "Bestätigen", user_friendship_path(friend, @friendship_this), method: :patch%>
            </div>
          </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'user-show-hide' %>
<%= javascript_pack_tag 'follow_button' %>