config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :ratings, only: [:new, :create]
  resources :friendships, only: [:new]
  resources :users, only: [:show, :edit] do
    resources :friendships, only: [:create, :show, :edit, :update]

  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <% if current_user.nil? %>
    <div class="footer-note">
<!--       <p>"Tripadvisor for friends" - wait, what? <i class="fas fa-arrow-circle-right"></i></p>
 -->
    </div>
  <% else %>
    <div class='home'>
      <%= link_to root_path do %>
        <i class="fas fa-home"></i>
      <%end %>
    </div>
    <div class='search'>
      <%= link_to new_friendship_path do %>
        <i class="fas fa-search"></i>
      <%end %>
    </div>
    <div class='profile'>
      <% if current_user.nil? %>
      <% else %>
        <%= link_to user_path(current_user) do %>
          <i class="far fa-user"></i>
        <%end %>
        <% if @friends_application == [] %>
        <% else %>
          <div class="counter">
            <%= @friends_application.count %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Add button -->
  <div class="navbar-wagon-left">
    <% if user_signed_in? %>
      <%= link_to new_rating_path do  %>
        <i class="far fa-plus-square"></i>
      <% end %>
    <% else %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Logo -->



  <div class="foodiees-navbar">

      <% if params[:controller] == 'users' && params[:action] == 'show' || params[:action] == 'edit'  %>
        <h4><%= current_user.first_name %> <%= current_user.last_name %> </h4>
      <% else %>
        <h1>foodiees</h1>
      <% end %>

  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <% if params[:controller] == 'users' && params[:action] == 'show'%>
        <%= link_to edit_user_path(current_user) do %>
          <div class="profile-edit-navbar">
            <i class="fas fa-cog"></i>
          </div>
        <%end %>
      <% elsif params[:controller] == 'users' &&  params[:action] == 'edit' %>
        <%= link_to user_path(current_user) do %>
          <div class="profile-edit-navbar">
            <i class="fas fa-check-circle"></i>
          </div>
        <%end %>
      <% elsif params[:controller] == 'devise/registrations' &&  params[:action] == 'edit' %>
        <%= link_to user_path(current_user) do %>
          <div class="profile-edit-navbar">
            <i class="far fa-caret-square-left"></i>
          </div>
        <%end %>
      <% else  %>
        <div class="navbar-bookie-item">
          <div class="dropdown">
            <% if current_user %>
              <div class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
                <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar" %>
              </div>
            <ul class="dropdown-menu dropdown-menu-right navbar-bookie-dropdown-menu">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
      <% if params[:controller] == 'users' && params[:action] == 'show'%>
        <%= link_to edit_user_path(current_user) do %>
          <div class="profile-edit-navbar">
            <i class="fas fa-cog"></i>
          </div>
        <%end %>
      <% elsif params[:controller] == 'users' &&  params[:action] == 'edit' %>
        <%= link_to user_path(current_user) do %>
          <div class="profile-edit-navbar">
            <i class="fas fa-check-circle"></i>
          </div>
        <%end %>
      <% elsif params[:controller] == 'devise/registrations' &&  params[:action] == 'edit' %>
        <%= link_to user_path(current_user) do %>
          <div class="profile-edit-navbar">
            <i class="far fa-caret-square-left"></i>
          </div>
        <%end %>
      <% else %>
        <div class="dropdown">
          <div class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
            <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar" %>
          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
              <%= link_to edit_user_path(current_user) do %>
                <i class="fas fa-user-edit"></i> <span>Settings</span>
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    <%else %>
      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>