config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :ratings, only: [:new, :create]
  resources :friendships, only: [:new]
  resources :users, only: [:show, :edit] do
    resources :friendships, only: [:create, :show, :edit, :update]

  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"

  validates :user_id, uniqueness: { scope: :friend_id }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def new
    @all = Friendship.all
    if params[:query].present?
      sql_query = "first_name ILIKE :query OR last_name ILIKE :query"
      @users = User.where(sql_query, query: "%#{params[:query]}%")

      @friends = []
      current_user.friendships.each do |friendship|
        @friends << friendship.friend_id
      end


      @new_users1 = @users.select do |user|
        @friends.include?(user.id) == false
      end

      @new_users = @new_users1.select do |user|
        user.id != current_user.id
      end

      # @users.each do |user|
      #   @new_friendships = user.friendships.select do |friendship|
      #     friendship.friend_id =f= current_user.id
      #     raise
      #   end
      # end

      # @new_users = @users.select do |user|
      #   @all.include?(user) == false
      # end
    else
      @users = nil
    end
  end

  def show
    @user_show = User.find(params[:user_id])
    @friendships_bestätigt = @user_show.friendships.select do |friendship|
      friendship.status = 'accepted'
    end

    @friends_bestätigt = []
    @friendships_bestätigt.each do |friendship|
      @friends_bestätigt << friendship.friend
    end
  end

  def create
    # eine Seite der Freunschaft
    @friendship = Friendship.new
    @friendship.user_id = current_user.id
    @friend = User.find(params[:user_id])
    @friendship.friend_id = @friend.id
    @friendship.action = "yes"
    @friendship.save
    # andere Seite der Freunschaft
    @friendship_second = Friendship.new
    @friendship_second.friend_id = current_user.id
    @user = User.find(params[:user_id])
    @friendship_second.user_id = @user.id
    @friendship_second.save
  end

  def edit
  end

  def update
    @user = User.find(params[:user_id])
    @friendship = @user.friendships.where(friend_id:current_user).first
    @friendship.status = 'accepted'
    @friendship_two = current_user.friendships.where(friend_id: @user.id).first
    @friendship_two.status = 'accepted'
    @friendship.save
    @friendship_two.save
  end

  private

  def friendship_params
     params.require(:friendship).permit(:status)
  end
end

app/views/friendships/new.html.erb
<div class="wrapper">
  <div class="search-home">
    <%= form_tag new_friendship_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class:"form-control",
      placeholder: "Search for a friend"
      %>
<!--       <%= button_tag :submit do %>
        <i class="fas fa-search"></i>
      <% end %> -->
    <% end %>
  </div>

  <div class="display-friends">
    <% if @new_users.nil? %>
      <div style="margin-top:15px;margin-bottom:15px">
        <div class="line"></div>
      </div>
    <% else %>
      <% @new_users.each do |user| %>
        <div style="margin-top:15px;margin-bottom:15px">
          <div class="line"></div>
        </div>
        <div class="users-info">
          <div class="profile-photo">
            <%= cl_image_tag user.photo, width: 140, height: 140, crop: :thumb, gravity: :face, class:"avatar" %>
          </div>
          <div class="name">
            <%= user.first_name %>
            <%= user.last_name %>
          </div>
          <div class="follow-button" >
            <%= link_to "Follow", user_friendships_path(user), method: :post%>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'follow_button' %>

app/views/friendships/show.html.erb
<div class="wrapper">
  <div class="friends-header">
    <h4>Friends</h4>
  </div>
  <% @friends_bestätigt.each do |friend| %>
    <div class="all-friends-show">
      <div class="friend-photo-user-details">
        <div class="friends-user-photo">
          <%= cl_image_tag friend.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar"%>
        </div>
        <div class="friends-user-details">
          <h4><%= friend.first_name %> <%= friend.last_name %></h4>
          <p> <%= friend.ratings.count %> reviews </p>
        </div>
      </div>
      <div class="unfollow-button">
        <%= link_to "Unfriend", root_path, method: :post%>
      </div>
    </div>
  <% end %>
</div>