config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :ratings, only: [:new, :create]
  resources :friendships, only: [:new]
  resources :users, only: [:show, :edit] do
    resources :friendships, only: [:create, :show, :edit, :update]

  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :ratings
  has_many :users, through: :ratings
  has_many :favorites

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def liked?(user)
    return unless user
    user.favorite_restaurants.include?(self) if user.favorite_restaurants
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def home
  end

  def index
    # @all = Friendship.all
    # @new_friendships = Friendship.all.select do |f|
    #   f.user_id == current_user.id or f.friend_id == current_user.id
    # end
    # @friends = []
    # @new_friendships.each do |friendship|
    #   if current_user.id == friendship.user_id
    #     @friends << friendship.friend
    #   else
    #     @friends << friendship.user
    #   end
    # end

    @friendships = current_user.friendships.where(status:'accepted')
    @friends = []
    @friendships.each do |friendship|
      @friends << friendship.friend
    end


    @restaurants_list = []
    @friends.each do |friend|
      @restaurants_list << friend.restaurants
    end
    @restaurants_pure = []
    @restaurants_list.each do |restaurant|
      restaurant.each do |r|
        @restaurants_pure << r
      end
    end

    # @unique = @restaurants_pure.uniq{ |d| d[:name]}

# find all names of the restaurants to see which names are double
    @arr = []
    @restaurants_pure.each do |restaurant|
      @arr << restaurant.name
    end

# find all double names
    @doubles = @arr.find_all { |e| @arr.count(e) > 1 }.uniq

#find all restaurants that are not listed more than once
    @restaurants_ohne_doubles = []

    @restaurants_pure.each do |restaurant|
      if @doubles.exclude?(restaurant.name) == true
        @restaurants_ohne_doubles << restaurant
      end
    end

# list all restaurants that are duplicates
    @restaurants_doubles = []
    @restaurants_pure.each do |restaurant|
      if @doubles.exclude?(restaurant.name) == false
        @restaurants_doubles << restaurant
      end
    end




    if params[:city].present?

      # @restaurants = @restaurants_pure(city: params[:city])
      @restaurants_ohne = @restaurants_ohne_doubles.select do |restaurant|
        restaurant.city.casecmp(params[:city].strip) == 0
      end
      # @restaurants = @restaurants_list.where(city: params[:city])
    else
      @restaurants_ohne = []
    end

    if params[:city].present?

      # @restaurants = @restaurants_pure(city: params[:city])
      @restaurants_mit = @restaurants_doubles.select do |restaurant|
        restaurant.city.casecmp(params[:city].strip) == 0
      end
      # @restaurants = @restaurants_list.where(city: params[:city])
    else
      @restaurants_mit = []
    end
    @restaurants_mit = @restaurants_mit.group_by { |d| d[:name] }



    @restaurant_first = @restaurants_mit.first

    # @all_users = []
    # @restaurants_mit.each do |restaurant|
    #   @all_users << restaurant.users
    # end

    if params[:city].present?

      # @restaurants = @restaurants_pure(city: params[:city])
      @restaurants = @restaurants_doubles.select do |restaurant|
        restaurant.city == params[:city]
      end
      # @restaurants = @restaurants_list.where(city: params[:city])
    else
      @restaurants = []
    end

    #index map

    @restaurants_all_map = []
    @restaurants_ohne.each do |restaurant|
      @restaurants_all_map << restaurant
    end
    @restaurants_mit.each do |restaurant|
      restaurant.second.each do |restaurant|
        @restaurants_all_map << restaurant
      end
    end


    @restaurants_map = @restaurants_all_map.select do |restaurant|
      restaurant.latitude != nil && restaurant.longitude != nil
    end



    @markers = @restaurants_map.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end

    @average_ohne = average_ohne
    @average_mit = average_mit
  end

  def show
    @restaurant_show = Restaurant.find(params[:id])
    @restaurant_show = Restaurant.all.where(name: @restaurant_show.name)

    @friend_ids = []
    current_user.friendships.each do |friendship|
      @friend_ids << friendship.friend_id
    end
    @restaurants_new = []
    @restaurant_show.each do |restaurant|
      if @friend_ids.include?(restaurant.user_ids[0])
        @restaurants_new << restaurant
      end
    end

    @average = average_show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
    else
      render :new
    end

  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :zipcode, :country, :city, :place_id)
  end

  def average_ohne

    sum = 0
    number = 0
    @restaurants_ohne.each do |restaurant|
      restaurant.ratings.each do |rating|
        number += 1
        sum += rating.stars
      end
    end
    @average = (sum.to_f/number.to_f).to_f.round(1)
    return @average
  end

  def average_mit

    sum = 0
    number = 0
    @restaurants_mit.each do |restaurant|
      restaurant.second.each do |r|
        r.ratings.each do |rating|
          number += 1
          sum += rating.stars
        end
      end
    end
    @average = (sum.to_f/number.to_f).to_f.round(1)
    return @average
  end

  def average_show
    sum = 0
    number = 0
    @restaurants_new.each do |restaurant|
      restaurant.ratings.each do |rating|
        number += 1
        sum += rating.stars
      end
    end
    @average = (sum.to_f/number.to_f).to_f.round(1)
    return @average
  end

end

app/views/restaurants/home.html.erb
<div class="wrapper">

  <div class="search-home-1">
      <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city],
        class:"form-control",
        placeholder: "Search for city or friend"
        %>
<!--         <%= button_tag :submit do %>
          <i class="fas fa-search"></i>
        <% end %> -->
      <% end %>
  </div>

  <div class="header-home">
    <h1>Have you been there?</h1>
  </div>
  <!-- <div class="row"> -->
    <div class="cities-photos">
      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Wien",
        class:"form-control"
        %>
        <%= image_submit_tag('Vienna.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Wien</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Zürich",
        class:"form-control"
        %>
        <%= image_submit_tag('Zurich.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Zürich</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Auckland",
        class:"form-control"
        %>
        <%= image_submit_tag('Auckland.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Auckland</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "München",
        class:"form-control"
        %>
        <%= image_submit_tag('munich.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>München</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Vancouver",
        class:"form-control"
        %>
        <%= image_submit_tag('Vancouver.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Vancouver</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Düsseldorf",
        class:"form-control"
        %>
        <%= image_submit_tag('Dusseldorf.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Düsseldorf</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Frankfurt",
        class:"form-control"
        %>
        <%= image_submit_tag('Frankfurt.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Frankfurt</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Genf",
        class:"form-control"
        %>
        <%= image_submit_tag('Genf.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Genf</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Kopenhagen",
        class:"form-control"
        %>
        <%= image_submit_tag('Kopenhagen.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Kopenhagen</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Basel",
        class:"form-control"
        %>
        <%= image_submit_tag('Basel.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Basel</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Sydney",
        class:"form-control"
        %>
        <%= image_submit_tag('Amsterdam.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Sydney</h1>
        </div>
      </div>

      <div class="city1">
        <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :city,
        params[:city], :value => "Amsterdam",
        class:"form-control"
        %>
        <%= image_submit_tag('Amsterdam.jpg', class:"intro-image") %>
      <% end %>
        <div class="citytext1">
          <h1>Amsterdam</h1>
        </div>
      </div>
    </div>
  <!-- </div> -->




  <div class="header-home">
    <h1>Latest reviews</h1>
  </div>
  <div class="slideshow-container">
   <% if Rating.all.count < 3 %>
     <h1>There are no ratings yet</h1>
   <% else %>
    <% Rating.all.order('created_at DESC').take(3).each do |r| %>
      <%= link_to restaurant_path(r.restaurant) do %>
        <div class="mySlides1">
          <% if r.photo.blank?  %>
              <%= image_tag("munich.jpg") %>
            <% else %>
              <%= cl_image_tag r.photo %>
          <% end %>
          <div class="rating-description">
            <h4>"<%= r.header %>"</h4>
            <p>- <%= r.user.first_name %> <%= r.user.last_name %></p>
          </div>
    <!--         <div class="rating-photo">
                <p>- <%= r.user.first_name %> <%= r.user.last_name %></p>
            </div> -->
            <div class="rating-star">
              <i class="fas fa-star"></i> <%= r.stars.to_f %>
            </div>

            <div class="rating-rname-rcity">
              <p><%= r.restaurant.name%></p>
              <p><%= r.restaurant.city %></p>
            </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
      <a class="prev" onclick="plusSlides(-1, 0)">&#10094;</a>
      <a class="next" onclick="plusSlides(1, 0)">&#10095;</a>
  </div>
</div>



<%= javascript_pack_tag 'imageslider' %>
<%= javascript_pack_tag 'search' %>

app/views/restaurants/index.html.erb
<div class='wrapper'>
  <div class="tab-slider--nav">
    <ul class="tab-slider--tabs">
      <li class="tab-slider--trigger active" rel="tab1">List</li>
      <li class="tab-slider--trigger" rel="tab2">Map</li>
    </ul>
  </div>

  <div class="tab-slider--container">
    <div id="tab1" class="tab-slider--body">
      <div class="row">
        <!-- <div class="col-sm-8 col-sm-offset-2"> -->
          <div id="restaurants">

        <!-- all restaurants that have more than one review -->
            <% if @restaurants_mit == [] %>
            <% else %>
              <% @restaurants_mit.each do |array| %>

                <div class="restaurant-flex">
                <%= link_to restaurant_path(array.second) do %>

                    <div class="image-index">
                      <% unless array.second.first.ratings.first.photo.blank? %>
                        <%= cl_image_tag array.second.first.ratings.first.photo %>
                      <% else %>
                        <%= image_tag("munich.jpg") %>
                      <% end %>
                      <div class="wishlist-index">
                        <% if array.second.first.liked?(current_user) == true%>

                          <%= link_to restaurant_favorite_path(array.second.first, array.second.first.favorites), method: :delete do %>


                            <i class="fas fa-heart <%= array.second.first.liked?(current_user) ? "like" : "dislike"  %>" id='favorite-restaurant-<%= array.second.first.id %>'></i>
                          <% end %>
                        <%else %>

                          <%= link_to restaurant_favorites_path(array.second), method: :post, remote: true do %>
                            <i class="fas fa-heart <%= array.second.first.liked?(current_user) ? "like" : "dislike"  %>" id='favorite-restaurant-<%= array.second.first.id %>'></i>
                          <% end %>
                        <%end %>
                      </div>
                    </div>
                    <div class="text-index">
                      <div class="center-index-text">
                        <h4><%= array.second.first.name %></h4>
                        <p><%= array.second.first.city %></p>
                      </div>
                      <div class="stars-index">
                        <p><i class="fas fa-star"></i> <%= @average_mit %></p>
                      </div>
                      <div class="avatar-index">
                        <%= cl_image_tag array.second.first.users.first.photo, width: 140, height: 140, crop: :thumb, gravity: :face, class:"avatar"   %>
                        <div class="plus-number">
                          <% all = [] %>
                          <% array.second.each do |user| %>
                            <% all << user.name %>
                          <% end %>
                          <p>+<%= all.count - 1 %></p>
                        </div>
                      </div>
                    </div>

                 <!--  <div class="line"></div> -->
                  <% end %>
                 </div>
              <% end %>
            <% end %>


            <!-- all restaurants that have only one rating  -->

            <% @restaurants_ohne.each do |restaurant| %>

                <div class="restaurant-flex">
                  <%= link_to restaurant_path(restaurant) do %>
                    <div class="image-index">
                      <% unless restaurant.ratings.first.photo.blank? %>
                        <%= cl_image_tag restaurant.ratings.first.photo %>
                      <% else %>
                        <%= image_tag("munich.jpg") %>
                      <% end %>
                      <div class="wishlist-index">
                        <% if restaurant.liked?(current_user) == true %>

                          <%= link_to restaurant_favorite_path(restaurant, restaurant.favorites), method: :delete do %>


                          <i class="fas fa-heart <%= restaurant.liked?(current_user) ? "like" : "dislike"  %>" id='favorite-restaurant-<%= restaurant.id %>'></i>
                           <% end %>
                        <% else %>
                          <%= link_to restaurant_favorites_path(restaurant), method: :post, remote: true do %>
                            <i class="fas fa-heart <%= restaurant.liked?(current_user) ? "like" : "dislike"  %>" id='favorite-restaurant-<%= restaurant.id %>'></i>
                          <% end %>
                        <% end %>

                      </div>
                    </div>
                    <div class="text-index">
                      <div class="center-index-text">
                        <h4><%= restaurant.name %></h4>
                        <p><%= restaurant.city %></p>
                        <div class="atmosphere-index">
                          <p style='font-size: 11px; color: white;'><%= restaurant.ratings.first.atmosphere %></p>
                        </div>
                      </div>
                      <div class="stars-index">
                        <p><i class="fas fa-star"></i> <%= @average_ohne %></p>
                      </div>
                      <div class="avatar-index">
                        <% if restaurant.users.count > 1 %>
                          <%= cl_image_tag restaurant.users.first.photo, width: 140, height: 140, crop: :thumb, gravity: :face, class:"avatar"   %>
                          <div class="plus-number">
                            <p>+<%= restaurant.users.count - 1 %></p>
                          </div>
                        <% else %>
                          <%= cl_image_tag restaurant.users.first.photo, width: 140, height: 140, crop: :thumb, gravity: :face, class:"avatar"   %>
                        <% end %>

                      </div>
                    </div>

                <!-- <div class="line"></div> -->
                  <% end %>
              </div>
            <% end %>
          </div>
        <!-- </div> -->
      </div>
    </div>



    <div id="tab2" class="tab-slider--body">
      <div
        id="map"
        style="width: 100%;
        height: 600px;"
        data-markers="<%= @markers.to_json %>"
      ></div>
    </div>
  </div>
</div>
<!--  -->

app/views/restaurants/show.html.erb
<div class="wrapper-show">
  <div class="row-show">
    <div class="restaurant-description">

      <div class="image-show">
        <% unless @restaurant_show.first.ratings.first.photo.blank? %>
          <%= cl_image_tag @restaurant_show.first.ratings.first.photo %>
        <% else %>
          <%= image_tag("munich.jpg") %>
        <% end %>
      </div>
      <div class='zeile1'>
        <div class="text-show-name-under12">
          <p><%= @restaurant_show.first.name %></p>
        </div>
        <div class='zeile2'>
          <div class="zeile2-stars">
            <p><i class="fas fa-star"></i> <%= @average %></p>
          </div>
          <div class="zeile2-zahl">
            (<%= @restaurants_new.length %>)
          </div>
        </div>
      </div>
      <div class="text-show">
        <div class="Ort">
          <div class="marker">
            <%=  link_to "", ('https://www.google.com/maps/dir/?api=1&destination='+@restaurant_show.first.address), { :class=>"fas fa-map-marker-alt" }%>
          </div>
          <div class="text">
            <p> <%= @restaurant_show.first.address%>, <%= @restaurant_show.first.zipcode %> <%= @restaurant_show.first.city %></p>
          </div>
        </div>

        <div class="Telefon">
          <div class="marker">
            <p><i class="fas fa-phone"></i></p>
          </div>
          <div class="text">
            <div id='phone'></div>
          </div>
        </div>

        <div class="Website">
          <div class="marker">
            <p><i class="fas fa-file"></i></p>
          </div>
          <div class="text">
            <div id='website'> <%= link_to 'website'%></div>
          </div>
        </div>

        <div class="Öffnungszeiten">
          <div class="marker">
            <p><i class="fas fa-hourglass-start"></i></p>
          </div>
          <div class="text">
            <div id='opening-hours'></div>
          </div>
        </div>

        <div class="phone-number">
         <div id="placeid" style="display: none"><%=@restaurant_show.first.place_id %></div>
         <div id='phone'></div>
         <div id= "website"> </div>
         <div id= 'opening-hours'></div>
        </div>

      </div>
    </div>
  </div>
  <div class="line-show"></div>

</div>
<div class="wrapper-show-rating">
  <!-- <h2 class="review-header">Reviews</h2> -->
  <h2>Reviews</h2>
  <% @restaurant_show.each do |restaurant| %>
    <% if @friend_ids.include?(restaurant.user_ids[0]) == true %>
      <% restaurant.ratings.each do |r| %>
        <div class="reviews-show">
          <div class="reviews-avatar-info">
            <div class="reviews-avatar">
              <%= link_to user_path do %>
                <%= cl_image_tag r.user.photo, width: 140, height: 140, crop: :thumb, gravity: :face, class:"avatar-reviews"   %>
              <% end %>
            </div>
            <div class="reviews-info">
              <div class="reviews-info-name">
                <%= r.user.first_name %> <%= r.user.last_name  %>
              </div>
              <div class="reviews-info-date">
                <%= r.created_at.strftime("%b %Y") %>
              </div>
            </div>
          </div>
    <!--       <div class="reviews-stars">
            <%= r.stars %>
          </div> -->

          <div class="review-stars">
            <p><i class="fas fa-star"></i> <%= restaurant.ratings.first.stars.to_f %></p>
          </div>
        </div>
        <div class="reviews-description">
          <%= r.description %>
        </div>
  <!--     <div class="line-reviews">
      </div> -->
      <% end %>
    <% end %>
  <% end %>
</div>